/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    services: Service;
    projects: Project;
    'team-members': TeamMember;
    testimonials: Testimonial;
    submissions: Submission;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'services-page': ServicesPage;
    'about-page': AboutPage;
    'projects-page': ProjectsPage;
    'contact-page': ContactPage;
    'blog-page': BlogPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Blog articles (“Field Notes”). Save as draft to preview before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL name. Leave empty to generate from the title.
   */
  slug?: string | null;
  /**
   * Short summary shown on blog cards and in search results.
   */
  excerpt: string;
  /**
   * Optional. If empty, a branded contour cover is generated.
   */
  coverImage?: (number | null) | Media;
  category?: (number | null) | Category;
  author?: (number | null) | TeamMember;
  publishedDate: string;
  /**
   * Featured posts get the large “survey sheet” slot at the top of the blog.
   */
  featured?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional overrides for search engines.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * All images used on the website. Upload once, reuse anywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description of the image (used by search engines and screen readers).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog post categories (used for the filter chips on the blog).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL name. Leave empty to generate from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Founders / leadership shown on the Home and About pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * e.g. “Co-Founder · Land Surveyor”
   */
  role: string;
  bio: string;
  photo: number | Media;
  /**
   * Small specialty chips, e.g. TOPOGRAPHIC, GIS.
   */
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The six service lines. Shown on the Home page cards and the Services page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Position in the list (1 = first). Also used for the 01/02… numbering.
   */
  order: number;
  icon: 'survey' | 'construction' | 'planning' | 'interior' | 'landscape' | 'realestate';
  /**
   * Short paragraph shown on the Home page card.
   */
  description: string;
  /**
   * One-liner shown on the Services page card.
   */
  tagline: string;
  /**
   * Bullet list shown on the Services page card.
   */
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Portfolio entries shown on the Projects page (cards + map markers).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  category: 'Survey' | 'GIS' | 'Construction' | 'Planning' | 'Interior' | 'Landscape';
  /**
   * Shown on the card, e.g. “KIAMBU · -1.171, 36.836”.
   */
  locationLabel: string;
  /**
   * Latitude for the map marker.
   */
  lat: number;
  /**
   * Longitude for the map marker.
   */
  lng: number;
  description: string;
  /**
   * Optional photo. If empty, a branded gradient cover is used.
   */
  image?: (number | null) | Media;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client quotes shown on the Home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * Who said it, e.g. “Property Owner”.
   */
  authorTitle: string;
  /**
   * Project context, e.g. “Kiambu Subdivision”.
   */
  context?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries sent through the contact form. Read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  name: string;
  phone?: string | null;
  email: string;
  service?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  publishedDate?: T;
  featured?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  icon?: T;
  description?: T;
  tagline?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  locationLabel?: T;
  lat?: T;
  lng?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorTitle?: T;
  context?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand, navigation, contact details, footer and the big green CTA banner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  brandTagline: string;
  /**
   * Optional image logo. If empty, the built-in GeoSpark mark is used.
   */
  logo?: (number | null) | Media;
  /**
   * Links in the top navigation bar, in order.
   */
  nav?:
    | {
        label: string;
        /**
         * e.g. /services or /#team
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  navCtaLabel: string;
  navCtaHref: string;
  email: string;
  /**
   * Displayed phone number.
   */
  phone: string;
  /**
   * Phone number for tel: and WhatsApp links (no spaces).
   */
  phoneRaw: string;
  address: string;
  /**
   * Decorative coordinates shown in the footer.
   */
  coordsLabel?: string | null;
  responseTime?: string | null;
  ctaBadge?: string | null;
  ctaTitle?: string | null;
  ctaTitleGradient?: string | null;
  ctaText?: string | null;
  ctaButtonLabel?: string | null;
  ctaButtonHref?: string | null;
  footerBlurb?: string | null;
  /**
   * Link columns (e.g. “Who we are”, “Our services”).
   */
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  siteTitle: string;
  siteDescription: string;
  /**
   * Image shown when the site is shared on social media.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    badge?: string | null;
    title: string;
    titleGradient: string;
    intro: string;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    /**
     * Decorative floating survey labels (up to 4).
     */
    coords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The stat strip under the hero buttons.
     */
    stats?:
      | {
          /**
           * e.g. 120 or ±8
           */
          value: string;
          /**
           * e.g. + or % or mm
           */
          suffix?: string | null;
          label: string;
          /**
           * Count up from 0 when scrolled into view (numbers only).
           */
          animate?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    kicker?: string | null;
    heading?: string | null;
    sub?: string | null;
    cardCtaLabel?: string | null;
  };
  about?: {
    kicker?: string | null;
    heading?: string | null;
    missionText?: string | null;
    visionText?: string | null;
    linkLabel?: string | null;
    /**
     * The four value cards.
     */
    values?:
      | {
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  marquee?: {
    label?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  team?: {
    kicker?: string | null;
    heading?: string | null;
  };
  testimonials?: {
    kicker?: string | null;
    heading?: string | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero: {
    kicker: string;
    /**
     * First (plain) part of the headline.
     */
    title: string;
    /**
     * Second part of the headline, shown in the green-blue gradient.
     */
    titleGradient: string;
    intro: string;
    /**
     * Decorative floating survey labels around the hero (up to 4). Hidden on small screens.
     */
    coords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    kicker?: string | null;
    heading?: string | null;
    steps?:
      | {
          /**
           * e.g. “01 · BRIEF”
           */
          step: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    kicker?: string | null;
    heading?: string | null;
    items?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    kicker: string;
    /**
     * First (plain) part of the headline.
     */
    title: string;
    /**
     * Second part of the headline, shown in the green-blue gradient.
     */
    titleGradient: string;
    intro: string;
    /**
     * Decorative floating survey labels around the hero (up to 4). Hidden on small screens.
     */
    coords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  story?: {
    kicker?: string | null;
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  mission?: {
    title?: string | null;
    text?: string | null;
  };
  vision?: {
    title?: string | null;
    text?: string | null;
  };
  /**
   * The four small value cards.
   */
  values?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  timeline?: {
    kicker?: string | null;
    heading?: string | null;
    items?:
      | {
          /**
           * e.g. FOUNDED
           */
          label: string;
          title: string;
          desc: string;
          color?: ('accent' | 'emerald') | null;
          id?: string | null;
        }[]
      | null;
  };
  team?: {
    kicker?: string | null;
    heading?: string | null;
  };
  tech?: {
    kicker?: string | null;
    heading?: string | null;
    chips?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  hero: {
    kicker: string;
    /**
     * First (plain) part of the headline.
     */
    title: string;
    /**
     * Second part of the headline, shown in the green-blue gradient.
     */
    titleGradient: string;
    intro: string;
    /**
     * Decorative floating survey labels around the hero (up to 4). Hidden on small screens.
     */
    coords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  map?: {
    centerLat?: number | null;
    centerLng?: number | null;
    zoom?: number | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    kicker: string;
    /**
     * First (plain) part of the headline.
     */
    title: string;
    /**
     * Second part of the headline, shown in the green-blue gradient.
     */
    titleGradient: string;
    intro: string;
    /**
     * Decorative floating survey labels around the hero (up to 4). Hidden on small screens.
     */
    coords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  form?: {
    /**
     * Options in the “What do you need?” dropdown.
     */
    serviceOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    servicePlaceholder?: string | null;
    messagePlaceholder?: string | null;
    submitLabel?: string | null;
    directLabel?: string | null;
    successTitle?: string | null;
    successText?: string | null;
    successButton?: string | null;
  };
  office?: {
    lat?: number | null;
    lng?: number | null;
    zoom?: number | null;
    popupTitle?: string | null;
    popupSubtitle?: string | null;
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  hero: {
    kicker: string;
    /**
     * First (plain) part of the headline.
     */
    title: string;
    /**
     * Second part of the headline, shown in the green-blue gradient.
     */
    titleGradient: string;
    intro: string;
    /**
     * Decorative floating survey labels around the hero (up to 4). Hidden on small screens.
     */
    coords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  featuredLabel?: string | null;
  allCategoriesLabel?: string | null;
  readLabel?: string | null;
  minReadLabel?: string | null;
  emptyText?: string | null;
  backToLogLabel?: string | null;
  relatedLabel?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandTagline?: T;
  logo?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  navCtaLabel?: T;
  navCtaHref?: T;
  email?: T;
  phone?: T;
  phoneRaw?: T;
  address?: T;
  coordsLabel?: T;
  responseTime?: T;
  ctaBadge?: T;
  ctaTitle?: T;
  ctaTitleGradient?: T;
  ctaText?: T;
  ctaButtonLabel?: T;
  ctaButtonHref?: T;
  footerBlurb?: T;
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        titleGradient?: T;
        intro?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        coords?:
          | T
          | {
              text?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              animate?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        kicker?: T;
        heading?: T;
        sub?: T;
        cardCtaLabel?: T;
      };
  about?:
    | T
    | {
        kicker?: T;
        heading?: T;
        missionText?: T;
        visionText?: T;
        linkLabel?: T;
        values?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  marquee?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        kicker?: T;
        heading?: T;
      };
  testimonials?:
    | T
    | {
        kicker?: T;
        heading?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        titleGradient?: T;
        intro?: T;
        coords?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        kicker?: T;
        heading?: T;
        steps?:
          | T
          | {
              step?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        kicker?: T;
        heading?: T;
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        titleGradient?: T;
        intro?: T;
        coords?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        kicker?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  mission?:
    | T
    | {
        title?: T;
        text?: T;
      };
  vision?:
    | T
    | {
        title?: T;
        text?: T;
      };
  values?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        kicker?: T;
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              title?: T;
              desc?: T;
              color?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        kicker?: T;
        heading?: T;
      };
  tech?:
    | T
    | {
        kicker?: T;
        heading?: T;
        chips?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        titleGradient?: T;
        intro?: T;
        coords?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  map?:
    | T
    | {
        centerLat?: T;
        centerLng?: T;
        zoom?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        titleGradient?: T;
        intro?: T;
        coords?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  form?:
    | T
    | {
        serviceOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        servicePlaceholder?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        directLabel?: T;
        successTitle?: T;
        successText?: T;
        successButton?: T;
      };
  office?:
    | T
    | {
        lat?: T;
        lng?: T;
        zoom?: T;
        popupTitle?: T;
        popupSubtitle?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        titleGradient?: T;
        intro?: T;
        coords?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  featuredLabel?: T;
  allCategoriesLabel?: T;
  readLabel?: T;
  minReadLabel?: T;
  emptyText?: T;
  backToLogLabel?: T;
  relatedLabel?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}